docker:
  db: {}
domains: []
global:
  name: event
  type: app
  version: 6.1.5
test:
  coverage:
    last_report:
      covered: 215
      excluded: 2
      missing: 5
      percent: 97.72727272727273
      total: 220
wex:
  migration: 1
  version: 6.0.112
