docker:
  db: {}
domains: []
global:
  name: event
  type: app
  version: 6.0.32
test:
  coverage:
    last_report:
      covered: 202
      excluded: 2
      missing: 1
      percent: 99.50738916256158
      total: 203
wex:
  version: 6.0.89
